version: "3"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: nginx_templater_kassy
    ports:
      - "80:80"
    depends_on:
      #      - mysql
      - python
    volumes:
      - ./static/:/static
      - ./media/:/media

  python:
    build:
      context: ./docker/python
      dockerfile: Dockerfile
    container_name: python_templater_kassy
    command: gunicorn calculator.wsgi:application -b 0.0.0.0:8000 --reload
    volumes:
      - ./backend/:/templater_kassy/backend
    ports:
      - "8000:8000"
#    env_file:
#      - .env
  #    depends_on:
  #      - mysql

  vue:
    build:
      context: ./docker/vue
      dockerfile: Dockerfile
    container_name: vue_templater_kassy
    volumes:
      - ./frontend:/templater_kassy/frontend
    working_dir: /templater_kassy/frontend
    command: bash -c "npm install && npm run serve"
    ports:
      - "8080:8080"
    depends_on:
      - python


#  networks:
#    django-nginx:
#      driver: bridge



#  mysql:
#    image: mysql:8.0
#    command: --default-authentication-plugin=mysql_native_password --skip_name_resolve
#    container_name: mysql
#    restart: always
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
#      - ./docker/mysql/conf.d:/etc/mysql/conf.d
#      - ./docker/mysql/dump:/tmp/dump
#      - ./tmp/log/docker:/var/log/mysql
#    ports:
#      - "3306:3306"
#    security_opt:
#      - seccomp:unconfined
#    environment:
#      MYSQL_DATABASE: calculatorBS
#      MYSQL_ROOT_PASSWORD: 12345
#      TZ: UTC
