FROM node:16.13.0

RUN mkdir /templater_kassy/
WORKDIR /templater_kassy/frontend

#COPY package*.json ./adv_calculator/frontend
#
#RUN npm cache verify
#
#RUN npm install
#
#COPY . .

EXPOSE 8080

# CMD ["npm", "run", "serve"]